### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by a Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [anders-liu/arduino-libs#1]
In the file "arduino-libs/AL_TCS3472/AL_TCS3472.cpp" in the function "read()", there is while-loop and a Wire.endTransmission() after the Wire.requestFrom(). Those can be removed, because there is nothing to wait for and the Wire.endTransmission() is only used when writing data.

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library.

All you need is this:
```
    uint8_t buffer[8];
    Wire.requestFrom((uint8_t)addr, (uint8_t)8);
    for (uint8_t i = 0; i < 8; i++)
    {
        buffer[i] = Wire.read();
    }
```

**Comment by anders-liu** [comment]
Good catch, will fix in next commit. Thank you very much!

**Comment by anders-liu** [comment]
#91d4b1448789280895cf7aaa7c1370a5a62ad13a

**Comment by anders-liu** [comment]
Fixed in commit https://github.com/anders-liu/arduino-libs/commit/91d4b1448789280895cf7aaa7c1370a5a62ad13a
